### ISSUE TITLE
Marketing Suggestions for landing page

### ISSUE THREAD

**Issue by n-jampen** [onehomecampaign/onehome-website#4]
-replace "Building Homes Together" with "How can you help?"
-replace "IRC" with "International Rescue Committee (IRC)" in the paragraph under the current text "Building Homes Together"...we also suggest to spell out IRC for the subheading
-replace "You don't have to donate directly in order to help OneHome to fundraise." with "There are other ways you can contribute."

**Comment by tbcooney** [comment]
updated..please close
